<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>usage-viewer.ico</ApplicationIcon>
    <AssemblyName>UsageViewer</AssemblyName>
    <RootNamespace>UsageViewer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="usage-viewer.ico" />
  </ItemGroup>
</Project>
